efi_loader: Allow overlapped extra data for PE hashing
During PE hashing, when holes exists between sections, the extra
data
calculated could be a dupulicated region of the last section.

Such PE image with holes existing between sections may contain the
symbol table for the kernel, for example.

The Authenticode_PE spec does not rule how to deal with such
scenario,
however, other tools such as pesign and sbsign both have the
overlapped
regions hashed. And EDK2 hash the overlapped area as well.

This fixes the following issue:

U-Boot 2024.01-g1d87afeffd (May 15 2024 - 10:12:14 +0200)

CPU:   Freescale i.MX8MMQ rev1.0 1600 MHz (running at 1200 MHz)
CPU:   Industrial temperature grade (-40C to 105C) at 52C
Reset cause: POR
DRAM:  2 GiB
optee optee: OP-TEE: revision 4.1 (a253ab8a)
Core:  151 devices, 28 uclasses, devicetree: separate
WDT:   Not starting watchdog@30280000
MMC:   FSL_SDHC: 0, FSL_SDHC: 1, FSL_SDHC: 2
Loading Environment from MMC... *** Warning - bad CRC, using default environment

In:    serial@30860000
Out:   serial@30860000
Err:   serial@30860000
Model: Toradex 0059 Verdin iMX8M Mini Quad 2GB IT V1.1D
Serial#: 15142023
Carrier: Toradex Verdin Development Board V1.1F, Serial# 11305480
Setting variant to nonwifi
Net:   eth0: ethernet@30be0000 [PRIME]
Hit any key to stop autoboot:  0
switch to partitions #0, OK
mmc1 is current device
Scanning mmc 1:1...
Card did not respond to voltage select! : -110
ERROR: invalid device tree
Found EFI removable media binary efi/boot/bootaa64.efi
124904 bytes read in 6 ms (19.9 MiB/s)
FT add OPTEE node
Booting /efi\boot\bootaa64.efi
efi_image_region_add: new region already part of another
Image not authenticated
efi_image_region_add: new region already part of another
Error loading \EFI\Linux\iris-6.9.0-iris_defconfig-d5203259011fc461d350d76f09e6ba89df74162541b58d9f03c2e869112e707a.efi
: Security Policy Violation
EFI LOAD FAILED: continuing...

Signed-off-by: Baocheng Su <baocheng.su at siemens.com>
Signed-off-by: Manuel Traut <manuel.traut@mt.com>